### ISSUE TITLE
Add support to Bitbucket

### ISSUE THREAD

**Issue by ivan-pinatti** [cloudposse/terraform-aws-jenkins#19]
Hi,

It would be nice to support Bitbucket as a source code repository for Jenkins Docker image.

We can take 2 different approaches;

1. Fork current module that supports Github and modify it to work with Bitbucket
2. Add support to Bitbucket in the module and have a variable to control which one to use

The module in question is [https://github.com/cloudposse/terraform-aws-cicd](https://github.com/cloudposse/terraform-aws-cicd)

I would like to hear your inputs @osterman and @aknysh because you have a more broader view about the solution and its directions.

Thanks in advance,

Ivan Pinatti

**Comment by aknysh** [comment]
@ivan-pinatti  thanks for the request.
Let me review CodePipeline and how it could support BitBucket and CodeCommit.
I'll get back to you shortly.

**Comment by ivan-pinatti** [comment]
Hi @aknysh,

A possible solution is to have a variable to select between Github/Bitbucket in this module and change the following variables to generic names;

- **_github_oauth_token_** to _git_provider_token_
- _**github_oauth_token**_ to _git_token_
- _**github_organization**_ to _git_organization_
- _**github_repo_name**_ to _git_repo_name_
- _**github_branch**_ to _git_branch_

This add-on would required logical changes in the following modules;

- https://github.com/cloudposse/terraform-aws-cicd
- https://github.com/cloudposse/terraform-aws-codebuild

We could use [Terraform conditionals](https://www.terraform.io/docs/configuration/interpolation.html#conditionals) to control the flow and implement the choosen one.
In this manner it wouldn't require to fork these modules, however, it would break current implementations because of the _github_oauth_token_ variable renaming, the other variables already have generic names in the other modules.

Basically, it will introduce changes in the variables passing from one module to another, modifications in the [CodeBuild](https://www.terraform.io/docs/providers/aws/r/codebuild_project.html) and [CodePipeline](https://www.terraform.io/docs/providers/aws/r/codepipeline.html) Terraform resources declaration / logic.

Lines affected;

**Jenkins**
- https://github.com/cloudposse/terraform-aws-jenkins/blob/master/main.tf#L123-L126
- https://github.com/cloudposse/terraform-aws-jenkins/blob/master/examples/new_vpc_new_subnets/main.tf#L29-L32
- https://github.com/cloudposse/terraform-aws-jenkins/blob/master/examples/existing_vpc_existing_subnets/main.tf#L29-L32
- https://github.com/cloudposse/terraform-aws-jenkins/blob/master/examples/existing_vpc_new_subnets/main.tf#L29-L32

**CI/CD**
- https://github.com/cloudposse/terraform-aws-cicd/blob/master/main.tf#L150
- https://github.com/cloudposse/terraform-aws-cicd/blob/master/main.tf#L192
- https://github.com/cloudposse/terraform-aws-cicd/blob/master/main.tf#L197
- https://github.com/cloudposse/terraform-aws-cicd/blob/master/main.tf#L262
- https://github.com/cloudposse/terraform-aws-cicd/blob/master/main.tf#L267

**CodeBuild**
- https://github.com/cloudposse/terraform-aws-codebuild/blob/master/main.tf#L109-L113

Let me hear your thoughts on this after you analysis.

Cheers,

Ivan Pinatti

**Comment by ivan-pinatti** [comment]
I forgot to mention these lines too;

**Jenkins**
- https://github.com/cloudposse/terraform-aws-jenkins/blob/master/variables.tf#L96-L118

**CI/CD**
- https://github.com/cloudposse/terraform-aws-cicd/blob/master/variables.tf#L33-L35
- https://github.com/cloudposse/terraform-aws-cicd/blob/master/variables.tf#L38
- https://github.com/cloudposse/terraform-aws-cicd/blob/master/variables.tf#L42
- https://github.com/cloudposse/terraform-aws-cicd/blob/master/variables.tf#L46

**CodeBuild**
- https://github.com/cloudposse/terraform-aws-codebuild/blob/master/variables.tf#L47-L50

**Comment by osterman** [comment]
Seems like a reasonable approach to me (renaming vars and using ternaries). Are there any additional variables that need to be added in order to support BitBucket?

I am alright with not maintaining backward compatibility since all modules have releases to ensure stability.

**Comment by ivan-pinatti** [comment]
@osterman, by what is described in Terraform [CodeBuild](https://www.terraform.io/docs/providers/aws/r/codebuild_project.html) and [CodePipeline](https://www.terraform.io/docs/providers/aws/r/codepipeline.html) resource documentation it doesn't look like it will require any. Although, it is not expressly declared that supports Bitbucket, specially in the CodePipeline page.

Let's wait for @aknysh inputs as well.

**Comment by aknysh** [comment]
@ivan-pinatti  @osterman 

It looks like CodePipeline does not support BitBucket as Source (at least I could not find any mention of it in any doc). Maybe it could just work as GitHub? It does support S3, CodeCommit and GitHub:
https://docs.aws.amazon.com/codepipeline/latest/userguide/integrations-action-type.html
https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html

CodeBuild, on the other hand, does support BitBucket as Source (they added it not too long ago)
https://aws.amazon.com/about-aws/whats-new/2017/08/aws-codebuild-now-supports-atlassian-bitbucket-cloud-as-a-source-type/
https://stackoverflow.com/questions/41686602/im-trying-to-integrate-bitbucket-into-aws-code-pipeline-what-is-the-best-appro

If we want to use CodePipeline as the Source for CodeBuild (as we do now in our CICD module), then BitBucket is not supported in this mode. There are two ways to solve this:

1. Mirror a BitBucket repo to a CodeCommit repo, and then use CodeCommit as Source in CodePipeline (very easy change): https://blog.frugalops.com/ci-and-cd-with-aws-codepipeline-codebuild/

2. Use Webhooks to notify a remote service by issuing an HTTP POST when a commit is pushed to the repository. AWS Lambda receives the HTTP POST through Amazon API Gateway, and then downloads a copy of the repository. It places a zipped copy of the repository into a versioned S3 bucket. CodePipeline can then use the zip file in S3 as a source. https://aws.amazon.com/blogs/devops/integrating-git-with-aws-codepipeline/

These approaches with CodePipeline do not look ideal (too many moving parts).

I'll take a look how to integrate BitBucket with CodeBuild. We will have to eliminate the first stage in the CodePipeline (Source) and just leave the other two stages (Build and Deploy), and configure CodeBuild to use a Source from S3, BitBucket, GitHub or CodeCommit. All of these need to be tested.

Thanks

**Comment by ivan-pinatti** [comment]
Hi @aknysh @osterman,

I will definitely start doing some testings on this, I will keep you posted about my findings.

**Comment by ivan-pinatti** [comment]
@aknysh @osterman,

CodePipeline doesn't support Bitbucket. When I change the source in CodeBuild options in AWS console it shows right away a warning message on the top, see it below;

![image](https://user-images.githubusercontent.com/7431771/35402755-87e68eec-01cb-11e8-9d3c-c9d525c38bf2.png)

I've researched AWS forums and there are some threads asking for the feature to support Bitbucket, I made a +1 comment to give AWS more visibility and to keep me posted about updates. I suggest you guys do the same. The [thread is this one](https://forums.aws.amazon.com/thread.jspa?threadID=222646&tstart=0&messageID=826909#826909)

In my opinion we can leave this issue open until AWS releases it, I don't think that it will take much longer.

**Comment by aknysh** [comment]
@ivan-pinatti 
thanks
We can wait for AWS to add BitBucket to CodePipeline.
At the same time you could test CodeBuild with BitBucket, it does support it.

**Comment by ivan-pinatti** [comment]
@aknysh,

Yes, it is working great with CodeBuild and manual deploy to Elastic Beanstalk for now.
Let's wait for AWS to release the feature.

Thanks.

**Comment by mathieumalfeyt** [comment]
Any updates on this feature? Seems it is taking a while :)

**Comment by aknysh** [comment]
will close for now.
re-open if need BitBucket support and CodePipeline supports it

**Comment by linlinas** [comment]
Bitbucket support for CodePipeline is now in beta and is available to test. 
https://aws.amazon.com/about-aws/whats-new/2019/12/aws-codepipeline-now-supports-atlassian-bitbucket-cloud/
