### ISSUE TITLE
Add end-to-end HTTPS support

### ISSUE THREAD

**Issue by ivan-pinatti** [cloudposse/terraform-aws-jenkins#21]
Hi,

It would be nice to have the option to use end-to-end HTTPS, It could be a self-signed **OR** a valid one.

An example using self-signed would involve;

**Jenkins**

- Adding to https://github.com/cloudposse/jenkins/blob/master/Dockerfile
```
# configure HTTPS and disable HTTP
ENV URL="ci.company.com" \
    COMPANY_NAME="My Company" \
    COUNTRY_CODE="US"

RUN mkdir --parents /var/lib/jenkins \
    && openssl genrsa -out /var/lib/jenkins/key.pem \
    && openssl req -new \
                   -subj "/CN=${URL}/O=${COMPANY_NAME}/C=${COUNTRY_CODE}" \
                   -key /var/lib/jenkins/key.pem \
                   -out /var/lib/jenkins/csr.pem \
    && openssl x509 -req \
                    -days 365 \
                    -in /var/lib/jenkins/csr.pem \
                    -signkey /var/lib/jenkins/key.pem \
                    -out /var/lib/jenkins/cert.pem \
    && chown jenkins:jenkins /var/lib/jenkins/*.pem

ENV JENKINS_OPTS --httpPort=-1 \
                 --httpsPort=8083 \
                 --httpsCertificate=/var/lib/jenkins/cert.pem \
                 --httpsPrivateKey=/var/lib/jenkins/key.pem
```
- Change this line [https://github.com/cloudposse/jenkins/blob/master/Dockerfile#L34](https://github.com/cloudposse/jenkins/blob/master/Dockerfile#L34) to
```
EXPOSE 8083
```
- Change this line [https://github.com/cloudposse/jenkins/blob/master/Dockerrun.aws.json.template#L27](https://github.com/cloudposse/jenkins/blob/master/Dockerrun.aws.json.template#L27) to
```
      "ContainerPort": "8083"
```
- Add a 3rd step to [https://github.com/cloudposse/jenkins/blob/master/.ebextensions/04-jenkins.config](https://github.com/cloudposse/jenkins/blob/master/.ebextensions/04-jenkins.config) as described in [https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-singleinstance-docker.html](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-singleinstance-docker.html)

Then adjust the ElasticBeanstalk, SGs (security groups) and LB (load balancers) to accept HTTPS. Some examples;
- [TCP passthrough](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/https-tcp-passthrough.html)
- [End-to-end](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https-endtoend.html)

**Comment by aknysh** [comment]
@ivan-pinatti 
SSL is already supported by `terraform-aws-jenkins` and `terraform-aws-elastic-beanstalk-environment`.

You need to request a certificate in Amazon Certificate Manager for the Jenkins domain or subdomain (it could be one wildcard cert for the root domain and all subdomains).

Then enter the cert ARN here
https://github.com/cloudposse/terraform-aws-jenkins/blob/master/main.tf#L37

Elastic Beanstalk environment will be created with the certificate, and you'll be able to access the Jenkins master via SSL.

In this case, SSL is terminated at the load balancer, not the EC2 instances (which is a good practice).

**Comment by ivan-pinatti** [comment]
Hi @aknysh,

I understand that the SSL already works terminating at the LB, it is working on my environment already. However, I'm suggesting to have an end-to-end secure connection. Think like HIPAA compliant.

**Comment by aknysh** [comment]
@ivan-pinatti 
we'll review it and let you know what could be done.
thanks again for your help

**Comment by ivan-pinatti** [comment]
Hi @aknysh,

I did some PRs that are part of the proposed solution and it can help you to have more visibility about it.

They are just a draft.
I also included the **TIME_ZONE** as an extra option, which it would be nice to have as well.

Let me know you thoughts regarding it so far.

**Comment by aknysh** [comment]
will close for now
re-open if need to continue on this
