### ISSUE TITLE
AWS Code Pipeline - Deploy fails

### ISSUE THREAD

**Issue by julian-saunders** [cloudposse/terraform-aws-jenkins#27]
Hello.  

I have been playing around with terraform-aws-jenkins.  Thanks for making it public.

Everything is working for me in terms of Terraform.  The AWS Code Pipeline runs, but the very last step fails.  The deploy of https://github.com/cloudposse/jenkins to the Elastic Beanstalk docker host.

I have also tried this via the Elastic Beanstalk GUI using "Upload and Deploy" and the provided Dockerrun.aws.json.template file.  This also fails.

Digging around on the EC2 instance created by Elastic Beanstalk, I have noticed a sample python app has been deployed to docker, and with an ngnix configuration that I believe will not work with the Jenkins container. 

I can manually pull the Jenkins container from ECR, but then must reconfigure Ngnix to proxy to Jenkins.

Are you guys finding the deployment still works without issue?

**Comment by osterman** [comment]
@aknysh does this sound familiar? @ivan-pinatti did you run into this error?

**Comment by aknysh** [comment]
@julian-saunders 
thank you for testing the module.
we deployed it for many clients a few months ago without any issues.
will need to take a look at it again (maybe something changed like Terraform version or AWS).

If you can provide more details on the issue (error messages, screenshots), that would be great.

Note: you can't run `Dockerrun.aws.json.template` directly because it's a template with ENV vars being substituted here
https://github.com/cloudposse/jenkins/blob/master/buildspec.yml#L22
For testing you could run `envsubst < "Dockerrun.aws.json.template" > "Dockerrun.aws.json"` and then use the generated `Dockerrun.aws.json` from the AWS UI (you need to provide the ENV vars here https://github.com/cloudposse/jenkins/blob/master/Dockerrun.aws.json.template#L22)

thanks

**Comment by julian-saunders** [comment]
@aknysh 
Here is a screenshot from the Elastic Beanstalk UI.
<img width="1348" alt="screen shot 2018-05-15 at 09 37 06" src="https://user-images.githubusercontent.com/30797586/40047134-8f44bd60-5826-11e8-872e-21ca2cfe15ce.png">

Ah yes, I did already substitute the env vars in Dockerrun.aws.json.template.  I took the vars from the CodePipeline build phase logs.  I used latest as $STAGE.

The build phase is successful, and I can manually pull the docker container from ECR onto the Elastic Beanstalk EC2 instance.
<img width="254" alt="screen shot 2018-05-15 at 10 08 23" src="https://user-images.githubusercontent.com/30797586/40047658-fac07894-5827-11e8-8540-91baf91aacbf.png">

**Comment by aknysh** [comment]
@julian-saunders 
thanks
I'll check the entire stack again and let you know the results

**Comment by aknysh** [comment]
@julian-saunders 
sorry for the delay, we were busy with other projects.
going to review this...

**Comment by aknysh** [comment]
@julian-saunders 
I just tested the entire stack.
it deployed without any issues.

Here is the exact file that I used:

```hcl
variable "region" {
  type    = "string"
  default = "us-east-1"
}

variable "namespace" {
  type    = "string"
  default = "ak"
}

variable "name" {
  type    = "string"
  default = "app"
}

variable "stage" {
  type    = "string"
  default = "dev"
}

variable "description" {
  type    = "string"
  default = ""
}

variable "solution_stack_name" {
  type    = "string"
  default = "64bit Amazon Linux 2017.09 v2.8.3 running Docker 17.06.2-ce"
}

variable "vpc_id" {
  type    = "string"
  default = "vpc-XXXXXXXX"
}

variable "igw_id" {
  type    = "string"
  default = "igw-XXXXXXXX"
}

variable "vpc_cidr" {
  description = "CIDR for VPC"
  default     = "10.0.0.0/16"
}

variable "zone_id" {
  type    = "string"
  default = "XXXXXXXXXXXX"
}

variable "healthcheck_url" {
  type    = "string"
  default = "/login"
}

variable "loadbalancer_type" {
  type        = "string"
  default     = "application"
  description = "Load Balancer type, e.g. 'application' or 'classic'"
}

variable "security_groups" {
  type    = "list"
  default = []
}

# CI/CD - CodePipeline/CodeBuild
variable "github_oauth_token" {
  type    = "string"
  default = "XXXXXXXXXXXX"
}

variable "github_organization" {
  type    = "string"
  default = "cloudposse"
}

variable "github_repo_name" {
  type    = "string"
  default = "jenkins"
}

variable "github_branch" {
  type    = "string"
  default = "master"
}

# http://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref.html#build-env-ref-available
variable "build_image" {
  type    = "string"
  default = "aws/codebuild/docker:1.12.1"
}

# http://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref.html#build-env-ref-compute-types
variable "build_compute_type" {
  type    = "string"
  default = "BUILD_GENERAL1_SMALL"
}

variable "aws_account_id" {
  type        = "string"
  description = "AWS Account ID. Used as CodeBuild ENV variable when building Docker images. For more info: http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html"
  default     = "XXXXXXXXXXXX"
}

variable "image_tag" {
  type        = "string"
  description = "Docker image tag in the ECR repository, e.g. 'latest'. Used as CodeBuild ENV variable when building Docker images. For more info: http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html"
  default     = "latest"
}

variable "ssh_public_key_path" {
  description = "Directory to store SSH key pair"
  default     = "secrets"
}

data "aws_availability_zones" "available" {}

module "jenkins" {
  source      = "git::https://github.com/cloudposse/terraform-aws-jenkins.git?ref=master"
  namespace   = "${var.namespace}"
  name        = "${var.name}"
  stage       = "${var.stage}"
  description = "${var.description}"

  aws_account_id               = "${var.aws_account_id}"
  aws_region                   = "${var.region}"
  availability_zones           = ["${data.aws_availability_zones.available.names}"]
  solution_stack_name          = "${var.solution_stack_name}"
  vpc_id                       = "${module.vpc.vpc_id}"
  zone_id                      = "${var.zone_id}"
  public_subnets               = "${module.subnets.public_subnet_ids}"
  private_subnets              = "${module.subnets.private_subnet_ids}"
  healthcheck_url              = "${var.healthcheck_url}"
  loadbalancer_type            = "${var.loadbalancer_type}"
  security_groups              = ["${var.security_groups}"]
  ssh_key_pair                 = "test-1"
  loadbalancer_certificate_arn = ""

  github_oauth_token  = "${var.github_oauth_token}"
  github_organization = "${var.github_organization}"
  github_repo_name    = "${var.github_repo_name}"
  github_branch       = "${var.github_branch}"

  build_image        = "${var.build_image}"
  build_compute_type = "${var.build_compute_type}"
  image_tag          = "${var.image_tag}"

  datapipeline_config = {
    instance_type = "t2.small"
    email         = "test123@gmail.com"
    period        = "6 hours"
    timeout       = "60 Minutes"
  }

  env_vars = {
    # Jenkins master instance config
    JENKINS_AUTHORIZATION_STRATEGY = "Matrix"
    JENKINS_USER                   = "admin"
    JENKINS_PASS                   = "password1"
    JENKINS_NUM_EXECUTORS          = "0"

    # EC2 plugin config (to launch slaves on demand)
    JENKINS_SLAVE_CLOUD_NAME               = "${var.namespace}.${var.stage}.${var.name}.slave"
    JENKINS_SLAVE_REGION                   = "${var.region}"
    JENKINS_SLAVE_INSTANCE_CAP             = "50"
    JENKINS_SLAVE_AMI_ID                   = "${data.aws_ami.slave_ami.id}"
    JENKINS_SLAVE_SUBNET_ID                = "${module.subnets.private_subnet_ids[0]}"
    JENKINS_SLAVE_INSTANCE_PROFILE_ARN     = ""
    JENKINS_SLAVE_INSTANCE_TYPE            = "t2.small"
    JENKINS_SLAVE_NUM_EXECUTORS            = "4"
    JENKINS_SLAVE_INIT_SCRIPT              = ""
    JENKINS_SLAVE_USER_DATA                = ""
    JENKINS_SLAVE_REMOTE_ADMIN             = "root"
    JENKINS_SLAVE_IDLE_TERMINATION_MINUTES = "20"
    JENKINS_SLAVE_LAUNCH_TIMEOUT_SECONDS   = "300"
    JENKINS_SLAVE_STOP_ON_IDLE_TIMEOUT     = "true"
  }
}

# Find AMI with Java installed
# https://www.terraform.io/docs/providers/aws/d/ami.html
# http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html
# NOTE: AMIs are region specific
data "aws_ami" "slave_ami" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "owner-alias"
    values = ["amazon"]
  }

  filter {
    name   = "architecture"
    values = ["x86_64"]
  }

  filter {
    name   = "name"
    values = ["aws-elasticbeanstalk-amzn*x86_64-java8-hvm*"]
  }
}

module "vpc" {
  source                           = "git::https://github.com/cloudposse/terraform-aws-vpc.git?ref=master"
  namespace                        = "${var.namespace}"
  name                             = "${var.name}"
  stage                            = "${var.stage}"
  cidr_block                       = "${var.vpc_cidr}"
  assign_generated_ipv6_cidr_block = "true"
}

module "subnets" {
  source              = "git::https://github.com/cloudposse/terraform-aws-dynamic-subnets.git?ref=master"
  availability_zones  = ["${data.aws_availability_zones.available.names}"]
  namespace           = "${var.namespace}"
  name                = "${var.name}"
  stage               = "${var.stage}"
  region              = "${var.region}"
  vpc_id              = "${module.vpc.vpc_id}"
  igw_id              = "${module.vpc.igw_id}"
  cidr_block          = "${module.vpc.vpc_cidr_block}"
  nat_gateway_enabled = "true"
}
```

Jenkins was deployed

![image](https://user-images.githubusercontent.com/7356997/40569614-2ef43db8-6051-11e8-923c-e4dca54f26b8.png)

![image](https://user-images.githubusercontent.com/7356997/40569617-3ab60258-6051-11e8-89af-5aed835f67f9.png)


Please destroy everything and try again.

Make sure the CloudFormation stacks are OK and deployed w/o errors (if any of them failed, please manually destroy it before `terraform plan/apply`)

![image](https://user-images.githubusercontent.com/7356997/40569652-8d89226c-6051-11e8-9ad3-07bf8bb7239b.png)

Make sure the ECR has the image stored in the repo

![image](https://user-images.githubusercontent.com/7356997/40569682-c551ccbc-6051-11e8-8695-e6f8be6e865d.png)

And also make sure Elastic Beanstalk deployed the app w/o errors and was able to pull the image from the ECR repo

![image](https://user-images.githubusercontent.com/7356997/40569716-f1741430-6051-11e8-9e39-28dfcdc78b1c.png)

**Comment by julian-saunders** [comment]
@aknysh 
I've been using the example "existing_vpc_new_subnets", and therefore creating within an existing VPC.  I destroyed everything, and took your example above, which included creating a new VPC.

I updated the following:

variable "region" {
  type    = "string"
  default = "**eu-west-1**"
}
...
variable "zone_id" {
  type    = "string"
  default = "**xxxxxxxxxx**"
}
...
variable "github_oauth_token" {
  type    = "string"
  default = "**xxxxxxxxxxx**"
}
...
variable "aws_account_id" {
  type        = "string"
  description = "AWS Account ID. Used as CodeBuild ENV variable when building Docker images. For more info: http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html"
  default     = "**xxxxxxxxxx**"
}
...
ssh_key_pair                 = "**my-key**"

I also had to comment out **assign_generated_ipv6_cidr_block = "true"** under the vpc module.  Otherwise I received the following error: 

Error: module "vpc": "assign_generated_ipv6_cidr_block" is not a valid argument

The good news is it worked :-)  Thank you.

I destroyed everything, adapted this working example by removing the vpc module, and updated the references to module.vpc with the details of another vpc.  This was to attempt to create within an existing VPC.

On running I received the following error:

* module.jenkins.module.efs_backup.data.aws_subnet_ids.default: 1 error(s) occurred:

* module.jenkins.module.efs_backup.data.aws_subnet_ids.default: data.aws_subnet_ids.default: no matching subnet found for vpc with id vpc-85c5b6e3

I actually witnessed this before, and now recall working round this by running the subnet module prior to the jenkins module.  Sorry I didn't mentioned this before.   I did this again, but for the adapted working example, commenting out the jenkins module, running, thus creating the subnets, and then uncommenting the jenkins modules, running.

The terraform completed successfully, but the CodePipeline deployment failed.

Tested with:
Terraform v0.11.7
+ provider.aws v1.20.0
+ provider.null v1.0.0

**Comment by aknysh** [comment]
thanks @julian-saunders 
looks like there is a problem with VPC/subnets when deploying into an existing VPC.
i'll deploy the same setup as you did and let you know if I find any issues and how to fix them.

**Comment by Bartekus** [comment]
I can attest that following the steps outlined by @aknysh will result in fully functional and operational infrastructure! Awesome work!

**Comment by aknysh** [comment]
thanks @Bartekus !!

@julian-saunders 
we improved the module in the last few releases.
tested it many times, and other people tested it as well - the examples worked.
I'll close the issue for now, please reopen if you are still having problems
