### ISSUE TITLE
Version Problems

### ISSUE THREAD

**Issue by scottwinkler** [cloudposse/terraform-aws-jenkins#41]
I get a strange error for tags from one of the nested modules, even though i have tags set:

```
* module.jenkins.module.label_slaves.data.null_data_source.tags_as_list_of_maps: data.null_data_source.tags_as_list_of_maps: value of 'count' cannot be computed
```

tags:
```
...
  tags = {
    BusinessUnit = "ABC"
    Department   = "XYZZ"
  }
```
I am using terraform v0.11.13, null v2.1.2, random v2.1.2, aws v2.9.0. I am concerned that this module only works for a very particular set of versions or something like that.

Also, when I comment out all the references to the terraform-null-label module, I get new errors:

```
Error: Error running plan: 60 error(s) occurred:

* module.jenkins.module.efs_backup.module.datapipeline_label.output.namespace: Resource 'null_resource.default' does not have attribute 'triggers.namespace' for variable 'null_resource.default.triggers.namespace'
* module.jenkins.module.efs_backup.module.backups_label.output.name: Resource 'null_resource.default' does not have attribute 'triggers.name' for variable 'null_resource.default.triggers.name'

```

I am not so sure about this error. I tried switching to different versions of the null provider, but I get the same error no matter what.

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-jenkins/releases/tag/0.6.0
