### ISSUE TITLE
This should be registered in the module registry

### ISSUE THREAD

**Issue by scottwinkler** [cloudposse/terraform-aws-jenkins#42]
This module, and all other modules from cloudposse should be registered in the official terraform module registry located here: https://registry.terraform.io/. This might help with version locking as well

**Comment by darynmitchell** [comment]
https://registry.terraform.io/modules/cloudposse/jenkins/aws/0.5.0 ?

**Comment by scottwinkler** [comment]
Hi daryn,
Thank you for responding so quickly. Yes, I did see that last night, but it wasnt in the documentation or the examples. Also, the master branch source code is still deferring to all of its module using git source references, so although it's a great small step, really all the other modules should be put on the registry as well.

**Comment by osterman** [comment]
@scottwinkler 100% of our modules are on the terraform registry (it's where we get most of our traffic). If you find one that's not, that's a mistake and please bring it to our attention.

**Comment by scottwinkler** [comment]
@osterman thank you for pointing that out. At the very least there should be a link to the terraform module registry in the Readme, otherwise someone stumbling upon this repo wouldn't know.

Also, if you really do have all the modules in the registry, then the sources of all the modules should still be updated in this repository.  For example,

```
source      = "git::https://github.com/cloudposse/terraform-aws-elastic-beanstalk-application.git?ref=tags/0.1.6"
```

should be replaced with:

```
  source  = "cloudposse/elastic-beanstalk-application/aws"
  version = "0.1.6"
```

Also, the Readme + examples need to be updated to reflect this.

**Comment by aknysh** [comment]
will close for now
the module was converted to TF 0.12 https://github.com/cloudposse/terraform-aws-jenkins/releases/tag/0.6.0
