### ISSUE TITLE
Cannot compute value of count

### ISSUE THREAD

**Issue by richardj-bsquare** [cloudposse/terraform-aws-jenkins#44]
$ terraform --version
Terraform v0.11.13
+ provider.aws v2.9.0
+ provider.null v2.1.2
+ provider.random v2.1.2

$ terraform plan
...

Error: Error refreshing state: 2 error(s) occurred:

* module.jenkins_stage.module.cicd.aws_codepipeline.source_build: aws_codepipeline.source_build: value of 'count' cannot be computed
* module.jenkins_stage.module.cicd.aws_codepipeline.source_build_deploy: aws_codepipeline.source_build_deploy: value of 'count' cannot be computed

```
module "jenkins_stage" {
    source      = "git::https://github.com/cloudposse/terraform-aws-jenkins.git?ref=0.5.0"
    ...
}
```

**Comment by richardj-bsquare** [comment]
A workaround is to apply changes that target the beanstalk_environment and beanstalk_application, then the above has all the information it requires in the terraform state thus allowing the value of count to be computed (since the aforementioned items are the only variants passed to cicd module)...

For example:

terraform apply --target=module.jenkins_stage.module.elastic_beanstalk_application --target=module.jenkins_stage.module.elastic_beanstalk_environment

**Comment by aknysh** [comment]
@richardj-bsquare 
thanks for testing the module.
we know about the issue with counts - all modules were updated to the latest version of https://github.com/cloudposse/terraform-null-label, which has some complex logic which can throw the count errors in the top-level modules.
The workarounds are 

1) use `--target` as you mentioned
2) update all modules to use https://github.com/cloudposse/terraform-terraform-label which does not have those issues

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/terraform-aws-jenkins/releases/tag/0.6.0
