### ISSUE TITLE
Terraform 0.14.x not supported

### ISSUE THREAD

**Issue by arthurazr777** [cloudposse/terraform-aws-jenkins#60]
Hi,
I am trying to do a terraform init inside the complete example folder and this is the output I get:

> terraform init
> Initializing modules...
> - jenkins in ../..
> Downloading cloudposse/cicd/aws 0.11.1 for jenkins.cicd...
> - jenkins.cicd in .terraform/modules/jenkins.cicd
> Downloading cloudposse/codebuild/aws 0.27.0 for jenkins.cicd.codebuild...
> - jenkins.cicd.codebuild in .terraform/modules/jenkins.cicd.codebuild
> Downloading git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.21.0 for jenkins.cicd.codebuild.this...
> - jenkins.cicd.codebuild.this in .terraform/modules/jenkins.cicd.codebuild.this
> Downloading cloudposse/label/null 0.22.1 for jenkins.cicd.this...
> - jenkins.cicd.this in .terraform/modules/jenkins.cicd.this
> Downloading cloudposse/ecr/aws 0.29.1 for jenkins.ecr...
> - jenkins.ecr in .terraform/modules/jenkins.ecr
> Downloading git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.21.0 for jenkins.ecr.this...
> - jenkins.ecr.this in .terraform/modules/jenkins.ecr.this
> Downloading cloudposse/efs/aws 0.25.0 for jenkins.efs...
> - jenkins.efs in .terraform/modules/jenkins.efs
> Downloading cloudposse/route53-cluster-hostname/aws 0.9.0 for jenkins.efs.dns...
> - jenkins.efs.dns in .terraform/modules/jenkins.efs.dns
> Downloading cloudposse/label/null 0.22.1 for jenkins.efs.dns.this...
> - jenkins.efs.dns.this in .terraform/modules/jenkins.efs.dns.this
> Downloading cloudposse/label/null 0.22.1 for jenkins.efs.this...
> - jenkins.efs.this in .terraform/modules/jenkins.efs.this
> Downloading cloudposse/backup/aws 0.4.0 for jenkins.efs_backup...
> - jenkins.efs_backup in .terraform/modules/jenkins.efs_backup
> Downloading git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2 for jenkins.efs_backup.label_backup_role...
> - jenkins.efs_backup.label_backup_role in .terraform/modules/jenkins.efs_backup.label_backup_role
> Downloading git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2 for jenkins.efs_backup.this...
> - jenkins.efs_backup.this in .terraform/modules/jenkins.efs_backup.this
> Downloading cloudposse/elastic-beanstalk-application/aws 0.9.0 for jenkins.elastic_beanstalk_application...
> - jenkins.elastic_beanstalk_application in .terraform/modules/jenkins.elastic_beanstalk_application
> Downloading cloudposse/label/null 0.22.1 for jenkins.elastic_beanstalk_application.this...
> - jenkins.elastic_beanstalk_application.this in .terraform/modules/jenkins.elastic_beanstalk_application.this
> Downloading cloudposse/elastic-beanstalk-environment/aws 0.32.0 for jenkins.elastic_beanstalk_environment...
> - jenkins.elastic_beanstalk_environment in .terraform/modules/jenkins.elastic_beanstalk_environment
> Downloading cloudposse/route53-cluster-hostname/aws 0.9.0 for jenkins.elastic_beanstalk_environment.dns_hostname...
> - jenkins.elastic_beanstalk_environment.dns_hostname in .terraform/modules/jenkins.elastic_beanstalk_environment.dns_hostname
> Downloading cloudposse/label/null 0.22.1 for jenkins.elastic_beanstalk_environment.dns_hostname.this...
> - jenkins.elastic_beanstalk_environment.dns_hostname.this in .terraform/modules/jenkins.elastic_beanstalk_environment.dns_hostname.this
> Downloading cloudposse/label/null 0.22.1 for jenkins.elastic_beanstalk_environment.this...
> - jenkins.elastic_beanstalk_environment.this in .terraform/modules/jenkins.elastic_beanstalk_environment.this
> Downloading cloudposse/label/null 0.22.1 for jenkins.label_slaves...
> - jenkins.label_slaves in .terraform/modules/jenkins.label_slaves
> Downloading cloudposse/label/null 0.22.1 for jenkins.this...
> - jenkins.this in .terraform/modules/jenkins.this
> Downloading cloudposse/dynamic-subnets/aws 0.33.0 for subnets...
> - subnets in .terraform/modules/subnets
> Downloading cloudposse/label/null 0.22.0 for subnets.nat_instance_label...
> - subnets.nat_instance_label in .terraform/modules/subnets.nat_instance_label
> Downloading cloudposse/label/null 0.22.0 for subnets.nat_label...
> - subnets.nat_label in .terraform/modules/subnets.nat_label
> Downloading cloudposse/label/null 0.22.0 for subnets.private_label...
> - subnets.private_label in .terraform/modules/subnets.private_label
> Downloading cloudposse/label/null 0.22.0 for subnets.public_label...
> - subnets.public_label in .terraform/modules/subnets.public_label
> Downloading cloudposse/label/null 0.22.0 for subnets.this...
> - subnets.this in .terraform/modules/subnets.this
> Downloading cloudposse/utils/aws 0.2.0 for subnets.utils...
> - subnets.utils in .terraform/modules/subnets.utils
> Downloading cloudposse/label/null 0.22.0 for subnets.utils.this...
> - subnets.utils.this in .terraform/modules/subnets.utils.this
> Downloading cloudposse/label/null 0.22.1 for this...
> - this in .terraform/modules/this
> Downloading cloudposse/vpc/aws 0.18.1 for vpc...
> - vpc in .terraform/modules/vpc
> Downloading cloudposse/label/null 0.22.0 for vpc.label...
> - vpc.label in .terraform/modules/vpc.label
> Downloading cloudposse/label/null 0.22.0 for vpc.this...
> - vpc.this in .terraform/modules/vpc.this
> 
> Error: Unsupported Terraform Core version
> 
>   on .terraform/modules/jenkins.efs_backup.label_backup_role/versions.tf line 2, in terraform:
>    2:   required_version = ">= 0.12.0, < 0.14.0"
> 
> Module module.jenkins.module.efs_backup.module.label_backup_role (from
> git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2)
> does not support Terraform version 0.14.4. To proceed, either choose another
> supported Terraform version or update this version constraint. Version
> constraints are normally set for good reason, so updating the constraint may
> lead to other errors or unexpected behavior.
> 
> 
> Error: Unsupported Terraform Core version
> 
>   on .terraform/modules/jenkins.efs_backup.this/versions.tf line 2, in terraform:
>    2:   required_version = ">= 0.12.0, < 0.14.0"
> 
> Module module.jenkins.module.efs_backup.module.this (from
> git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.19.2)
> does not support Terraform version 0.14.4. To proceed, either choose another
> supported Terraform version or update this version constraint. Version
> constraints are normally set for good reason, so updating the constraint may
> lead to other errors or unexpected behavior.

Basically the efs_backup submodule doesn't seem to support 0.14.x since it is locked in <0.14.0

I have terraform 0.14.4

Appreciate your help with this

**Comment by nitrocode** [comment]
I think we need to upgrade the backup module to this version https://github.com/cloudposse/terraform-aws-backup/tree/0.10.4
